# -*- coding: utf-8 -*-
"""Add many nums

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgcC67CiPQy3znZdlVmm21odeG2TKqeX
"""

def add_many_numbers(numbers)-> int:
    """
    Takes in a list of numbers and returns the sum of those numbers.
    """

    total_so_far: int = 0
    for number in numbers:
        total_so_far += number

    return total_so_far

# There is no need to edit code beyond this point

def main():
    numbers: list[int] = [1, 2, 3, 4, 5]  # Make a list of numbers
    sum_of_numbers: int = add_many_numbers(numbers)  # Find the sum of the list
    print(sum_of_numbers)  # Print out the sum above


if __name__ == '__main__':
    main()

"""tho it doesn't feel right according to the question so here is my actual answer 👇"""

def sum_numbers(numbers) -> int:
    return sum(numbers)

def main():
    numbers = []
    n = int(input("How many numbers do you want to enter? "))
    for i in range(n):
        num = float(input(f"Enter number {i + 1}: "))
        numbers.append(num)

    result = sum_numbers(numbers)
    print("The sum of the numbers is:", result)

if __name__ == '__main__':
    main()