# -*- coding: utf-8 -*-
"""Double.list

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9_Bu17fKG-H8uhpO6irxDav2UgXz4LK
"""

def double_elements(numbers):
    for i in range(len(numbers)):
        numbers[i] = numbers[i] * 2
    return numbers

# Get user input for a list of numbers
user_input = input("Enter numbers separated by spaces: ")
numbers = [int(num) for num in user_input.split()]

# Call the function and print the result
doubled_numbers = double_elements(numbers)
print("Doubled numbers:", doubled_numbers)