# -*- coding: utf-8 -*-
"""Flowing with data structures

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYPMuIXaLc-P-_RsG9wiQr8ruUM0wm5g
"""

def add_three_copies(my_list, data):
    for i in range(3):
        my_list.append(data)

def main():
    message = input("Enter a message to copy: ")
    my_list = []
    print("List before:", my_list)
    add_three_copies(my_list, message)
    print("List after:", my_list)

if __name__ == "__main__":
    main()