# -*- coding: utf-8 -*-
"""E=mc**2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fu9RiinPRSw4vwwyjidZ4wU6sCFKEUhr
"""

def main():
    # Constant for the speed of light in meters per second
    c = 299792458  # m/s

    while True:
        # Ask the user for the mass in kilograms
        mass = float(input("Enter kilos of mass: "))

        # Calculate the energy using the formula E = m * c^2
        energy = mass * c ** 2

        # Output the results
        print(f"\nE = m * C^2...\n")
        print(f"m = {mass} kg")
        print(f"C = {c} m/s")
        print(f"{energy} joules of energy!\n")

if __name__ == "__main__":
    main()