# -*- coding: utf-8 -*-
"""Feet to inches

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLrJb19UcodHH1mqkwunZ9hCVVjjZGq6
"""

INCHES_IN_FOOT: int = 12  # There are 12 inches in 1 foot.

def main():
    feet: float = float(input("Enter number of feet: "))  # Ask user for feet and convert to float
    inches: float = feet * INCHES_IN_FOOT  # Convert feet to inches
    print("That is", inches, "inches!")  # Print the result

if __name__ == '__main__':
    main()