# -*- coding: utf-8 -*-
"""Pythagorean-theorem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJBWM_DNUO8D8ulLUzsu-01-svdWsYhX
"""

import math  # We import math to use the square root function

# Ask user for the lengths of the two sides
ab = float(input("Enter the length of AB: "))
ac = float(input("Enter the length of AC: "))

# Calculate the hypotenuse using Pythagorean theorem
bc = math.sqrt(ab**2 + ac**2)

# Print the result
print("The length of BC (the hypotenuse) is:", bc)