# -*- coding: utf-8 -*-
"""remainder-division

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJ4tUulIMhj6dxtFML9DFNWDhEJ-x3nS
"""

# Program to divide two numbers and find the remainder

# Asking user for two integers
num1 = int(input("Please enter an integer to be divided: "))
num2 = int(input("Please enter an integer to divide by: "))

# Performing division
quotient = num1 // num2  # Floor division to get whole number
remainder = num1 % num2  # Modulo to get remainder

# Printing the result
print(f"The result of this division is {quotient} with a remainder of {remainder}")