# -*- coding: utf-8 -*-
"""add_two_nums

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14adkajRROdJwr4eG72NfH7o7eskw6Dh8

#Add two numbers
"""

"""
Program: add2numbers
--------------------
Another python program to get some practice with
variables.  This program asks the user for two
integers and prints their sum.
"""


def main():
    print("This program adds two numbers.")
    num1 : str = input("Enter first number: ")
    num1 : int = int(num1)
    num2  : str = input("Enter second number: ")
    num2 : int = int(num2)
    total : int = num1 + num2
    print("The total is " + str(total) + ".")


# This provided line is required at the end of
# Python file to call the main() function.
if __name__ == '__main__':
    main()