# -*- coding: utf-8 -*-
"""Agreement-bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOuAIYp82wHbLFGujIXWobB6nLBMRfd_

#Agreement bot
"""

def main():

    favorite_animal = input("What's your favorite animal? ")


    print(f"\nMy favorite animal is also {favorite_animal}!")

if __name__ == "__main__":
    main()