# -*- coding: utf-8 -*-
"""fahrenheit to celsius

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmhBRI2SeLaZP8-brs_8T2ISATta_DNa
"""

def main():
  degrees_fahrenheit = float(input("Eneter temprature in fahrenheit: "))

  degrees_celsius = (degrees_fahrenheit -32) * 5.0/9.0

  print(f"\nTemperature: {degrees_fahrenheit}F = {degrees_celsius}C")

if __name__ == "__main__":
   main()