# -*- coding: utf-8 -*-
"""How-old-are-they

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxSjNrPJbyxXcZUmXjj28aVgWq_mUAwX
"""

def main():
  anton_age = 21


  beth_age = anton_age + 6
  chen_age = beth_age + 20
  drew_age = anton_age + chen_age
  ethan_age = chen_age

  print(f"Anton is {anton_age} years old.")
  print(f"Beth is {beth_age} years old.")
  print(f"Chen is {chen_age} years old.")
  print(f"drew is {drew_age} years old.")
  print(f"ethan is {ethan_age} years old.")

if __name__ == "__main__":
  main()