# -*- coding: utf-8 -*-
"""square-number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKnuEkzdQZCuoep4qe3WI0wmFhju9QRa
"""

def main():

  number = float(input("Type a number to see its square: "))

  square = number ** 2

  print(f"{number} squared is {square}")

if __name__ == "__main__":
  main()